# Generated by Django 4.2.22 on 2025-06-06 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        help_text="The original long URL to be shortened",
                        max_length=2048,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        help_text="The unique short code for the URL",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
