# Generated by Django 4.2.22 on 2025-06-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlmapping",
            name="access_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="urlmapping",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="urlmapping",
            index=models.Index(
                fields=["short_code"], name="url_shorten_short_c_e5fb80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urlmapping",
            index=models.Index(
                fields=["created_at"], name="url_shorten_created_1ba3a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urlmapping",
            index=models.Index(
                fields=["access_count"], name="url_shorten_access__aa8c6a_idx"
            ),
        ),
    ]
